# Generated by Django 5.2.6 on 2025-09-26 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_chef_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('units', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='meal_images')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.chef')),
            ],
        ),
    ]
