# Generated by Django 5.2.6 on 2025-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_meal_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
