# Generated by Django 5.2.6 on 2025-10-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_meal_options_meal_created_at_meal_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='avaliabilty_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
