# Generated by Django 5.2.6 on 2025-10-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_meal_avaliabilty_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='avaliabilty_status',
            new_name='avaliability_status',
        ),
    ]
