# Generated by Django 5.2.6 on 2025-11-15 15:56

import cart.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_rename_avaliabilty_status_meal_avaliability_status'),
        ('user', '0006_rename_accoun_name_chef_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_code', models.CharField(default=cart.models.generate_code, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='product.meal')),
            ],
        ),
    ]
