# Generated by Django 5.2.6 on 2025-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_chef_brand_name_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
