# Generated by Django 5.2.6 on 2025-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_chef_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='accoun_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chef',
            name='account_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='accoun_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='driver',
            name='account_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
