# Generated by Django 5.2.6 on 2025-11-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_chef_accoun_name_chef_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='accoun_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='accoun_name',
            new_name='account_name',
        ),
    ]
