# Generated by Django 5.2.6 on 2025-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_chef_created_at_chef_updated_at_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
